/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package b27ej1;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author quique
 */
public class Calculadora extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();

        bo0.addActionListener(this);
        bo1.addActionListener(this);
        bo2.addActionListener(this);
        bo3.addActionListener(this);
        bo4.addActionListener(this);
        bo5.addActionListener(this);
        bo6.addActionListener(this);
        bo7.addActionListener(this);
        bo8.addActionListener(this);
        bo9.addActionListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        texto = new javax.swing.JTextField();
        bosuma = new javax.swing.JButton();
        boresta = new javax.swing.JButton();
        bomulti = new javax.swing.JButton();
        bodivi = new javax.swing.JButton();
        boigual = new javax.swing.JButton();
        borrar = new javax.swing.JButton();
        bo1 = new javax.swing.JButton();
        bo2 = new javax.swing.JButton();
        bo3 = new javax.swing.JButton();
        bo4 = new javax.swing.JButton();
        bo5 = new javax.swing.JButton();
        bo6 = new javax.swing.JButton();
        bo7 = new javax.swing.JButton();
        bo8 = new javax.swing.JButton();
        bo9 = new javax.swing.JButton();
        bo0 = new javax.swing.JButton();
        bopunto = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("C4S10");

        texto.setEditable(false);
        texto.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        texto.setText("0");

        bosuma.setText("+");
        bosuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bosumaActionPerformed(evt);
            }
        });

        boresta.setText("-");
        boresta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borestaActionPerformed(evt);
            }
        });

        bomulti.setText("*");
        bomulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bomultiActionPerformed(evt);
            }
        });

        bodivi.setText("/");
        bodivi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bodiviActionPerformed(evt);
            }
        });

        boigual.setText("=");
        boigual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boigualActionPerformed(evt);
            }
        });

        borrar.setText("Borrar");
        borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarActionPerformed(evt);
            }
        });

        bo1.setText("1");

        bo2.setText("2");

        bo3.setText("3");

        bo4.setText("4");

        bo5.setText("5");

        bo6.setText("6");

        bo7.setText("7");

        bo8.setText("8");

        bo9.setText("9");

        bo0.setText("0");

        bopunto.setText(".");
        bopunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bopuntoActionPerformed(evt);
            }
        });

        jLabel2.setText("© CASIO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(texto))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(bopunto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bo7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(bo8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bo9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(bo0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bo4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bo5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bo6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bo1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bo2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bo3))
                            .addComponent(borrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bomulti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(boresta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bosuma, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bodivi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(boigual, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(texto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(borrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bo1)
                            .addComponent(bo2)
                            .addComponent(bo3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bo4)
                            .addComponent(bo5)
                            .addComponent(bo6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bo7)
                            .addComponent(bo8)
                            .addComponent(bo9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bo0)
                            .addComponent(bopunto)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bosuma)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boresta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bomulti)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bodivi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boigual)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    String nbotonpuls = "";
    String operacion, result, bot;
    int m = 0, op = 0;


    private void borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarActionPerformed
        nbotonpuls = "";
        this.texto.setText(null);
        this.jLabel1.setText(null);
        m = 0;
    }//GEN-LAST:event_borrarActionPerformed

    private void bosumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bosumaActionPerformed
        this.texto.setText(null);
        this.jLabel1.setText("+");
        operacionesCalc();
        op = 0;
        nbotonpuls = "";
        m++;
    }//GEN-LAST:event_bosumaActionPerformed

    private void borestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borestaActionPerformed
        this.texto.setText(null);
        this.jLabel1.setText("-");
        operacionesCalc();
        op = 1;
        nbotonpuls = "";
        m++;
    }//GEN-LAST:event_borestaActionPerformed

    private void bomultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bomultiActionPerformed
        this.texto.setText(null);
        this.jLabel1.setText("*");
        operacionesCalc();
        op = 2;
        nbotonpuls = "";
        m++;
    }//GEN-LAST:event_bomultiActionPerformed

    private void bodiviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bodiviActionPerformed
        this.texto.setText(null);
        this.jLabel1.setText("/");
        operacionesCalc();
        op = 3;
        nbotonpuls = "";
        m++;

    }//GEN-LAST:event_bodiviActionPerformed

    private void boigualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boigualActionPerformed
        operacionesCalc();
        operacion = result;
    }//GEN-LAST:event_boigualActionPerformed

    private void bopuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bopuntoActionPerformed
        bot = ".";
        nbotonpuls = nbotonpuls + bot;
        this.texto.setText(nbotonpuls);
    }//GEN-LAST:event_bopuntoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton bo0;
    public javax.swing.JButton bo1;
    public javax.swing.JButton bo2;
    public javax.swing.JButton bo3;
    public javax.swing.JButton bo4;
    public javax.swing.JButton bo5;
    public javax.swing.JButton bo6;
    public javax.swing.JButton bo7;
    public javax.swing.JButton bo8;
    public javax.swing.JButton bo9;
    public javax.swing.JButton bodivi;
    public javax.swing.JButton boigual;
    public javax.swing.JButton bomulti;
    public javax.swing.JButton bopunto;
    public javax.swing.JButton boresta;
    public javax.swing.JButton borrar;
    public javax.swing.JButton bosuma;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JTextField texto;
    // End of variables declaration//GEN-END:variables

    public void botonesActionPerformed(java.awt.event.ActionEvent evt) {

        Object ev = evt.getSource();

        if (ev.equals(bo1)) {

            bot = "1";
            nbotonpuls = nbotonpuls + bot;
            this.texto.setText(nbotonpuls);
        }

    }

    public void operacionesCalc() {

        if (m == 0) {
            operacion = nbotonpuls;
        } else {

            switch (op) {
                case 0:
                    operacion = String.valueOf((Float.parseFloat(operacion) + Float.parseFloat(nbotonpuls)));
                    this.texto.setText(operacion);
                    break;
                case 1:
                    operacion = String.valueOf((Float.parseFloat(operacion) - Float.parseFloat(nbotonpuls)));
                    this.texto.setText(operacion);
                    break;
                case 2:
                    m++;
                    result = String.valueOf((Float.parseFloat(operacion) * Float.parseFloat(nbotonpuls)));
                    this.texto.setText(result);
                    break;
                case 3:
                    m++;
                    result = String.valueOf((Float.parseFloat(operacion) / Float.parseFloat(nbotonpuls)));
                    this.texto.setText(result);
                    break;
                default:
                    System.out.println("Error");
                    break;
            }
        }
    }

    @Override
    public void actionPerformed(ActionEvent ae) {

        Object ev = ae.getSource();

        if (ev.equals(bo1)) {

            bot = "1";
            nbotonpuls = nbotonpuls + bot;
            this.texto.setText(nbotonpuls);
        } else if (ev.equals(bo2)) {
            bot = "2";
            nbotonpuls = nbotonpuls + bot;
            this.texto.setText(nbotonpuls);
        } else if (ev.equals(bo3)) {
            bot = "3";
            nbotonpuls = nbotonpuls + bot;
            this.texto.setText(nbotonpuls);
        } else if (ev.equals(bo4)) {
            bot = "4";
            nbotonpuls = nbotonpuls + bot;
            this.texto.setText(nbotonpuls);
        } else if (ev.equals(bo5)) {
            bot = "5";
            nbotonpuls = nbotonpuls + bot;
            this.texto.setText(nbotonpuls);
        } else if (ev.equals(bo6)) {
            bot = "6";
            nbotonpuls = nbotonpuls + bot;
            this.texto.setText(nbotonpuls);
        } else if (ev.equals(bo7)) {
            bot = "7";
            nbotonpuls = nbotonpuls + bot;
            this.texto.setText(nbotonpuls);
        } else if (ev.equals(bo8)) {
            bot = "8";
            nbotonpuls = nbotonpuls + bot;
            this.texto.setText(nbotonpuls);
        } else if (ev.equals(bo9)) {
            bot = "9";
            nbotonpuls = nbotonpuls + bot;
            this.texto.setText(nbotonpuls);
        } else if (ev.equals(bo0)) {
            bot = "0";
            nbotonpuls = nbotonpuls + bot;
            this.texto.setText(nbotonpuls);
        }

    }
}
