/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package b25ej1;

import java.awt.Point;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author quique
 */
public class Bonoloto extends javax.swing.JFrame {

    File urlImg;

    /**
     * Creates new form Bonoloto
     */
    public Bonoloto() {
        initComponents();

        ImageIcon Img = new ImageIcon((urlImg = new File("src/com/imagen/bonoloto.jpg")).getAbsolutePath());

        imagen.setIcon(Img);

        imagen.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tBonoloto = new javax.swing.JTable();
        imagen = new javax.swing.JLabel();
        nselec = new javax.swing.JTextField();
        random = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        jTextField2.setText("jTextField2");

        jTextField3.setText("jTextField3");

        jTextField4.setText("jTextField4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tBonoloto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, "1", "2", "3", "4"},
                {"5", "6", "7", "8", "9"},
                {"10", "11", "12", "13", "14"},
                {"15", "16", "17", "18", "19"},
                {"20", "21", "22", "23", "24"},
                {"25", "26", "27", "28", "29"},
                {"30", "31", "32", "33", "34"},
                {"35", "36", "37", "38", "39"},
                {"40", "41", "42", "43", "44"},
                {"45", "46", "47", "48", "49"}
            },
            new String [] {
                "", "", "", "", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tBonoloto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tBonolotoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tBonoloto);
        if (tBonoloto.getColumnModel().getColumnCount() > 0) {
            tBonoloto.getColumnModel().getColumn(0).setResizable(false);
            tBonoloto.getColumnModel().getColumn(1).setResizable(false);
            tBonoloto.getColumnModel().getColumn(2).setResizable(false);
            tBonoloto.getColumnModel().getColumn(3).setResizable(false);
            tBonoloto.getColumnModel().getColumn(4).setResizable(false);
        }

        nselec.setEditable(false);
        nselec.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        random.setText("Random");
        random.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                randomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(random)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nselec, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nselec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(random))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    String numero = null, completo = "";
    String[] numeroSeleccionado = new String[6];
    int i = 0;
    private void tBonolotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tBonolotoMouseClicked
        try {
            Point punto = this.tBonoloto.getMousePosition();

            int fila = this.tBonoloto.rowAtPoint(punto);
            int columna = this.tBonoloto.columnAtPoint(punto);

            numero = (String) this.tBonoloto.getValueAt(fila, columna);

            numeroSeleccionado[i] = numero;

            completo = completo + numero + " ";

            nselec.setText(completo);
            i++;

            if (i == 6) {

                numerosMaquina();
            }

        } catch (ArrayIndexOutOfBoundsException ex) {
            JOptionPane.showMessageDialog(null, "Ya has seleccionado 6 números.");
        }
    }//GEN-LAST:event_tBonolotoMouseClicked

    private void randomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_randomActionPerformed

        for (int j = 0; j < numeroSeleccionado.length; j++) {
            numRandom = (int) (Math.random() * (50) + 1);
            numeroSeleccionado[j] = String.valueOf(numRandom);

        }
        numerosMaquina();
    }//GEN-LAST:event_randomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bonoloto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bonoloto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bonoloto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bonoloto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bonoloto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imagen;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField nselec;
    private javax.swing.JButton random;
    public javax.swing.JTable tBonoloto;
    // End of variables declaration//GEN-END:variables

    int numRandom;
    String[] nRandom = new String[6];

    public void numerosMaquina() {

        for (int j = 0; j < numeroSeleccionado.length; j++) {
            numRandom = (int) (Math.random() * (50) + 1);
            nRandom[j] = String.valueOf(numRandom);

        }
        comparar();
    }

    public void comparar() {
        int aciertos = 0;

        for (int j = 0; j < nRandom.length; j++) {
            System.out.println("Tu numero: " + numeroSeleccionado[j]);
            System.out.println("Premiado: " + nRandom[j]);
            for (int k = 0; k < numeroSeleccionado.length; k++) {
                if (nRandom[j].equals(numeroSeleccionado[k])) {
                    aciertos++;
                }
            }
        }

        System.out.println("Numero de aciertos: " + aciertos);

        nselec.setText("");
        completo = "";
        numero = "";
        i = 0;
    }

}
